# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false
  displayName: creating files

- script: mvn compile -X
  displayName: compiling
  workingDirectory: my-app

- script: mvn package -X
  displayName: packaging
  workingDirectory: my-app

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'my-app/target/my-app-1.0-SNAPSHOT.jar'
    artifactName: my-app-1.0-SNAPSHOT

# - task: Docker@2
#   displayName: Login to Docker Hub
#   inputs:
#     command: login
#     containerRegistry: dockerRegistryServiceConnection2

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'Docker Hub'
    Dockerfile: Dockerfile
    command: buildAndPush
    repository: tonyschneider/devops-exercise-image
    tags: 1.0-SNAPSHOT

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    command: 'start'
    repository: tonyschneider/devops-exercise-image
    tags: 1.0-SNAPSHOT