# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# resources:
#   containers:
#   - container: devops-exercise-container
#     image: tonyschneider/devops-exercise-image:1.0-SNAPSHOT

steps:
- script: mvn compile -X
  displayName: compiling
  workingDirectory: my-app

- script: mvn package -X
  displayName: packaging
  workingDirectory: my-app

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'my-app/target/my-app-1.0-SNAPSHOT.jar'
    artifactName: my-app-1.0-SNAPSHOT

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'Docker Hub'
    Dockerfile: Dockerfile
    command: buildAndPush
    repository: tonyschneider/devops-exercise-image
    tags: 1.0-SNAPSHOT

# - task: Docker@2
#   inputs:
#     command: start
#     container: devops-exercise-container

- script: |
    docker pull tonyschneider/devops-exercise-image:1.0-SNAPSHOT
    docker run -d -p 8080:8080 tonyschneider/devops-exercise-image:1.0-SNAPSHOT
  displayName: running the docker
